-- Reminder split: REMINDER_1_DAY, REMINDER_3_DAY, REMINDER_2_HOUR
-- Plus: GOOGLE_MAPS_REVIEW, TEAM_INVITE_LINK, CUSTOMER_VERIFY_LINK

BEGIN;

DO $$ BEGIN
  ALTER TYPE "AppointmentMessageEventType" ADD VALUE IF NOT EXISTS 'REMINDER_1_DAY';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TYPE "AppointmentMessageEventType" ADD VALUE IF NOT EXISTS 'REMINDER_3_DAY';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TYPE "AppointmentMessageEventType" ADD VALUE IF NOT EXISTS 'REMINDER_2_HOUR';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TYPE "AppointmentMessageEventType" ADD VALUE IF NOT EXISTS 'GOOGLE_MAPS_REVIEW';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TYPE "AppointmentMessageEventType" ADD VALUE IF NOT EXISTS 'TEAM_INVITE_LINK';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TYPE "AppointmentMessageEventType" ADD VALUE IF NOT EXISTS 'CUSTOMER_VERIFY_LINK';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

COMMIT;
